=== AlpetGexha/UPZ-TIT/Semestri_6/Webi Dinamik/det2/kontaktet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="kontaktet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="kontakti" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="personi">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="emri">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[A-Za-z]+"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="mbiemri">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[A-Za-z]+"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="adresa">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="zipKodi">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="[0-9]{5}"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="rruga" type="xs:string"/>
                    <xs:element name="qyteti" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="telefoni" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="telefoniType">
                      <xs:attribute name="lloji" default="mobil">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="mobil"/>
                            <xs:enumeration value="fiks"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="emailAdresa">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z0-9._%+-]*@[a-zA-Z0-9.-]*\.[a-zA-Z]{2,}|"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:simpleType name="telefoniType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== AlpetGexha/UPZ-TIT/Semestri_6/Webi Dinamik/det2/kontaktet_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<kontaktet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="kontaktet.xsd">
    <kontakti>
        <personi>
            <emri>Filan</emri>
            <mbiemri>Fisteku</mbiemri>
        </personi>
        <adresa>
            <zipKodi>10000</zipKodi>
            <rruga>Rr. Gjergj Fishta</rruga>
            <qyteti>Prishtine</qyteti>
        </adresa>
        <telefoni lloji="fiks">029-123-456</telefoni>
        <telefoni lloji="mobil">044-124-356</telefoni>
        <emailAdresa>filan.fisteku@gmail.com</emailAdresa>
    </kontakti>
    <kontakti>
        <personi>
            <emri>Test</emri>
            <mbiemri>Testi</mbiemri>
        </personi>
        <adresa>
            <zipKodi>20000</zipKodi>
            <rruga>Rr. Zahir Pajaziti</rruga>
            <qyteti>Prizren</qyteti>
        </adresa>
        <telefoni lloji="fiks">029-126-453</telefoni>
        <emailAdresa></emailAdresa>
    </kontakti>
    <kontakti>
        <personi>
            <emri>Filan</emri>
            <mbiemri>Testi</mbiemri>
        </personi>
        <adresa>
            <zipKodi>30000</zipKodi>
            <rruga>Rr. Adem Jashari</rruga>
            <qyteti>Prizren</qyteti>
        </adresa>
        <telefoni lloji="mobil">049-126-435</telefoni>
        <emailAdresa>test.testi@gmail.com</emailAdresa>
    </kontakti>
</kontaktet>
